/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import controlador.ControlFacturacion;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Factura;
import modelo.Producto;

/**
 *
 * @author cezun
 */
public final class GUIFacturacion extends javax.swing.JFrame {
    
    private final ControlFacturacion control;
    private Cliente cliente;
    private Producto producto;
       
    private Object[][] data;
    private final String [] columnas = {"Codigo","Nombre","Precio","Cantidad"};
    private DefaultTableModel dtm;
    private int codigo = 0;
    private String nombre;
    private String fechaFacutra;
    private int cantidad;
    private final Date fecha = new Date();
    private double totalSinIva = 0;
    private final float IVA = (float) 0.19; 
    private double totalConIva = 0;
    private final String formatoFecha = "dd-MM-yyyy";
    private final SimpleDateFormat fechaSimple = new SimpleDateFormat(formatoFecha);
    private float ivaActual;
    
    /**
     * Creates new form GUIFacturacion
     */
    public GUIFacturacion() {
        control = new ControlFacturacion(); 
        dtm = new DefaultTableModel(data, columnas);
        initComponents();
        
        iniciarFactura();
        tablaProductosPedido.setModel(dtm);
        tablaProductosPedido.repaint();
        
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbNumFactura = new javax.swing.JLabel();
        txtFactura = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        lbFecha = new javax.swing.JLabel();
        txtAtendido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtIdentificacion = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        lbIdentificacion = new javax.swing.JLabel();
        lbNombres = new javax.swing.JLabel();
        lbApellidos = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnAgregarPro = new javax.swing.JButton();
        btnEliminarPro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductosPedido = new javax.swing.JTable();
        txtCantidad = new javax.swing.JTextField();
        lbTotal1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lbSubtotal = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        lbIva = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        lbTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        txtEfectivo = new javax.swing.JTextField();
        txtCambio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 65, 81));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lbTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setText("FACTURACIÓN");

        jPanel2.setBackground(new java.awt.Color(25, 65, 81));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        lbNumFactura.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        lbNumFactura.setForeground(new java.awt.Color(255, 255, 255));
        lbNumFactura.setText("N° Factura:");

        txtFactura.setEditable(false);
        txtFactura.setBackground(new java.awt.Color(204, 204, 204));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(204, 204, 204));

        lbFecha.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        lbFecha.setForeground(new java.awt.Color(255, 255, 255));
        lbFecha.setText("Fecha:");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Atendido por:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAtendido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbNumFactura)
                                    .addGap(28, 28, 28)
                                    .addComponent(txtFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbFecha)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4))
                        .addGap(0, 62, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtFactura, txtFecha});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumFactura)
                    .addComponent(txtFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAtendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtFactura, txtFecha});

        jPanel3.setBackground(new java.awt.Color(25, 65, 81));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        txtIdentificacion.setMinimumSize(new java.awt.Dimension(5, 20));

        txtNombres.setEditable(false);
        txtNombres.setBackground(new java.awt.Color(204, 204, 204));
        txtNombres.setMinimumSize(new java.awt.Dimension(5, 20));

        txtApellidos.setEditable(false);
        txtApellidos.setBackground(new java.awt.Color(204, 204, 204));
        txtApellidos.setMinimumSize(new java.awt.Dimension(5, 20));

        txtCorreo.setEditable(false);
        txtCorreo.setBackground(new java.awt.Color(204, 204, 204));
        txtCorreo.setMinimumSize(new java.awt.Dimension(5, 20));

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(204, 204, 204));
        txtTelefono.setMinimumSize(new java.awt.Dimension(5, 20));

        btnBuscarCliente.setForeground(new java.awt.Color(25, 65, 81));
        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnBuscarCliente.setText("BUSCAR");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        lbIdentificacion.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        lbIdentificacion.setForeground(new java.awt.Color(255, 255, 255));
        lbIdentificacion.setText("Identificación:");

        lbNombres.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        lbNombres.setForeground(new java.awt.Color(255, 255, 255));
        lbNombres.setText("Nombres:");

        lbApellidos.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        lbApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lbApellidos.setText("Apellidos:");

        lbDireccion.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        lbDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lbDireccion.setText("Correo:");

        lbTelefono.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        lbTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lbTelefono.setText("Teléfono:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbIdentificacion)
                    .addComponent(lbNombres)
                    .addComponent(lbApellidos)
                    .addComponent(lbDireccion)
                    .addComponent(lbTelefono))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarCliente))
                    .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtApellidos, txtCorreo, txtIdentificacion, txtNombres, txtTelefono});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(btnBuscarCliente)
                    .addComponent(lbIdentificacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNombres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDireccion)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelefono))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtApellidos, txtCorreo, txtIdentificacion, txtNombres, txtTelefono});

        jPanel4.setBackground(new java.awt.Color(25, 65, 81));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N

        btnAgregarPro.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnAgregarPro.setForeground(new java.awt.Color(25, 65, 81));
        btnAgregarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas_opt.png"))); // NOI18N
        btnAgregarPro.setText("AGREGAR");
        btnAgregarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProActionPerformed(evt);
            }
        });

        btnEliminarPro.setForeground(new java.awt.Color(25, 65, 81));
        btnEliminarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/basura_opt.png"))); // NOI18N
        btnEliminarPro.setText("ELIMINAR");
        btnEliminarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProActionPerformed(evt);
            }
        });

        tablaProductosPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProductosPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosPedidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductosPedido);

        lbTotal1.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        lbTotal1.setForeground(new java.awt.Color(255, 255, 255));
        lbTotal1.setText("Cantidad:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAgregarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarPro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbTotal1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPro)
                    .addComponent(btnEliminarPro)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelar.setForeground(new java.awt.Color(25, 65, 81));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar (1)_opt.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setForeground(new java.awt.Color(25, 65, 81));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image (1).png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lbSubtotal.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        lbSubtotal.setForeground(new java.awt.Color(255, 255, 255));
        lbSubtotal.setText("Subtotal:  ");

        txtSubtotal.setEditable(false);
        txtSubtotal.setBackground(new java.awt.Color(153, 153, 153));

        lbIva.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        lbIva.setForeground(new java.awt.Color(255, 255, 255));
        lbIva.setText("IVA:");

        txtIva.setEditable(false);
        txtIva.setBackground(new java.awt.Color(153, 153, 153));

        lbTotal.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        lbTotal.setForeground(new java.awt.Color(255, 255, 255));
        lbTotal.setText("Total:");

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(153, 153, 153));

        txtDescuento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescuentoFocusLost(evt);
            }
        });

        txtEfectivo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEfectivoFocusLost(evt);
            }
        });

        txtCambio.setEditable(false);
        txtCambio.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descuento:");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Efectivo $:");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cambio:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(lbTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCancelar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbSubtotal)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(42, 42, 42)
                                                .addComponent(lbIva))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(69, 69, 69)
                                                .addComponent(lbTotal))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(145, 145, 145)
                                        .addComponent(btnGuardar)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtIva, txtSubtotal, txtTotal});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSubtotal)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIva)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtIva, txtSubtotal, txtTotal});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        String botones[] = {"Confirmar", "Cancelar"};
        int opcion = JOptionPane.showOptionDialog(this, "¿Esta seguro de cerrar Facturación? Se perderá los datos no guardados", "Confirmar", 0, 0, null, botones, this);
        if(opcion == JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProActionPerformed
        // TODO add your handling code here:
        GUIProductos guiProductos = new GUIProductos(control);
        guiProductos.setVisible(true);
    }//GEN-LAST:event_btnAgregarProActionPerformed
        
    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        int identificacion = esNumero(txtIdentificacion.getText());
        if(identificacion != -1){
            cliente = control.buscarCliente(identificacion);
            if(cliente != null){
                txtNombres.setText(cliente.getNombres());
                txtApellidos.setText(cliente.getApellidos());
                txtCorreo.setText(cliente.getCorreo());
                txtTelefono.setText(cliente.getTelefono());
            }else{
                JOptionPane.showMessageDialog(this, "No se encontro cliente con ese numero de identificacion");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe ingresar solo numeros");
        }        
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnEliminarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProActionPerformed
        // TODO add your handling code here:
        int filaSelecionada, respuestaOpcion, cantidadSelecionada;
        
        filaSelecionada = tablaProductosPedido.getSelectedRow();
        if(filaSelecionada == -1){
           JOptionPane.showMessageDialog(this, "Debe Seleccionar un producto a eliminar","Advertencia",JOptionPane.WARNING_MESSAGE); 
        }else{            
            respuestaOpcion = JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar la cantidad asignada de este producto","Eliminar",JOptionPane.YES_NO_OPTION);
             if(respuestaOpcion == JOptionPane.YES_OPTION){
                cantidadSelecionada = esNumero(txtCantidad.getText());
                nombre = tablaProductosPedido.getValueAt(filaSelecionada, 1).toString();
                producto = control.buscarProductoPedido(nombre);
                if(cantidadSelecionada == producto.getCantidad()){
                    codigo = Integer.parseInt(tablaProductosPedido.getValueAt(filaSelecionada, 0).toString());
                    boolean elimino = control.eliminarProductoPedido(codigo);
                    if(elimino){
                        eliminarDetalleProducto(filaSelecionada);
                    }else{
                        JOptionPane.showMessageDialog(this, "El producto no pudo ser eliminado");
                    }
                }else{
                    producto.setCantidad(producto.getCantidad() - Integer.parseInt(txtCantidad.getText()));
                    eliminarDetalleProducto(filaSelecionada);
                }                    
            }
        }
    }//GEN-LAST:event_btnEliminarProActionPerformed

    private void eliminarDetalleProducto(int filaSelecionada){
        double precioProducto, totalEliminado;        
        precioProducto = Double.parseDouble(tablaProductosPedido.getValueAt(filaSelecionada,2).toString()) * Integer.parseInt(txtCantidad.getText());
        totalEliminado = Double.parseDouble(txtTotal.getText()) - precioProducto;
        totalConIva = totalEliminado;
        String totalConIvaString = String.format("%.0f", totalConIva);
        txtTotal.setText(totalConIvaString);
        ivaActual = (float) (totalConIva*IVA);
        String ivaActualString = String.format("%.0f", ivaActual);
        txtIva.setText(ivaActualString);
        totalSinIva = totalEliminado - ivaActual;
        String totalSinIvaString = String.format("%.0f", totalSinIva);
        txtSubtotal.setText(totalSinIvaString);
        mostrarProductos();
        obtenerValores();
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            obtenerValores();
            fechaFacutra = txtFecha.getText();
            if(cliente == null){
            JOptionPane.showMessageDialog(this, "Debe selecionar un cliente primero");
            }else{
                Factura factura = new Factura(fecha, totalSinIva, ivaActual, totalConIva, cliente);
                boolean agregada = control.agregarFactura(factura);
                if(agregada){
                    JOptionPane.showMessageDialog(this, "Fecha: " + fechaFacutra + "\n\n"
                            + "Atendido por: " + txtAtendido.getText()
                            + "Factura numero: " + control.obtenerCodigo() + " generada con exito\n\n"
                            + "A nombre de: " + cliente.getNombres() + " " + cliente.getApellidos() + "\n\n"
                            + "Subtotal de: " + totalSinIva + "\n\n"
                            + "Iva de: " + ivaActual + "\n\n"
                            + "Para un total de: " + totalConIva + "\n\n");
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "No se pudo agregar factura, rectificar campos");
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Debe agregar al menos un producto");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tablaProductosPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosPedidoMouseClicked
        // TODO add your handling code here:
        int filaSelecionada = tablaProductosPedido.rowAtPoint(evt.getPoint());
        cantidad = Integer.parseInt(tablaProductosPedido.getValueAt(filaSelecionada, 3).toString());
        txtCantidad.setText(""+cantidad);
    }//GEN-LAST:event_tablaProductosPedidoMouseClicked

    private void txtDescuentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescuentoFocusLost
        // TODO add your handling code here:
        descuento();
    }//GEN-LAST:event_txtDescuentoFocusLost

    private void txtEfectivoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEfectivoFocusLost
        // TODO add your handling code here:
        cambio();
    }//GEN-LAST:event_txtEfectivoFocusLost

    private int esNumero(String entrada){
        int numero;
        try{
            numero = Integer.parseInt(entrada);
            return numero;
        }catch(NumberFormatException nfe){
            return -1;
        }
    }
    
    private void mostrarProductos(){
        data = control.mostrarProductoPedido();
        dtm = new DefaultTableModel(data, columnas);
        tablaProductosPedido.setModel(dtm);
        tablaProductosPedido.repaint();
    }
    
    private void iniciarFactura(){
        control.setCodigo(++codigo);
        txtFactura.setText(""+control.obtenerCodigo());
        txtFecha.setText(fechaSimple.format(fecha));
    }
    
    private void descuento(){
        float descuento, iva;
        double totalDescuento, total, sub;
        if(!txtDescuento.getText().isEmpty()){
            obtenerValores();
            total = totalConIva;
            sub = totalSinIva;
            descuento = (float) esNumero(txtDescuento.getText())/100;
            totalDescuento = (total*descuento);
            total -= totalDescuento;
            if(total >=0){
                iva  = (float) (total*IVA);
                sub -= iva;
                String subTotalFormat = String.format("%.0f", sub);
                String ivaProductoFormat = String.format("%.0f", iva);
                String totalFormat = String.format("%.0f", total);
                txtSubtotal.setText(""+subTotalFormat);
                txtIva.setText(""+ivaProductoFormat);
                txtTotal.setText(""+totalFormat);
            }
        }
    }
    
    private void obtenerValores(){
        totalConIva = Double.parseDouble(txtTotal.getText());
        totalSinIva = Double.parseDouble(txtSubtotal.getText());
        ivaActual = Float.parseFloat(txtIva.getText());
    }
    
    private void cambio(){
        double efectivo, cambio;
        if(!txtEfectivo.getText().isEmpty()){
            obtenerValores();
            efectivo = (double) esNumero(txtEfectivo.getText());
            if(efectivo > totalConIva){
                cambio = efectivo - totalConIva;
                String cambioFormat = String.format("%.0f", cambio);
                txtCambio.setText(cambioFormat);
            }else{
                txtCambio.setText(""+0);
            }            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
             
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUIFacturacion().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPro;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarPro;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbIdentificacion;
    private javax.swing.JLabel lbIva;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JLabel lbNumFactura;
    private javax.swing.JLabel lbSubtotal;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTotal1;
    public static javax.swing.JTable tablaProductosPedido;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtAtendido;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtEfectivo;
    private javax.swing.JTextField txtFactura;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdentificacion;
    public static javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtNombres;
    public static javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTelefono;
    public static javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
