/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControlFacturacion;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;

/**
 *
 * @author cezun
 */
public class GUIProductos extends javax.swing.JFrame {
    
    private final ControlFacturacion control;
    private Object[][] data;
    private final String columnas[] = {"Codigo","Nombre","Precio","Cantidad"};
    private DefaultTableModel dtm;
    private Producto producto;
    private int codigo;
    private String nombre;
    private double precio;
    private int cantidad;
    private String descripcion;
    private double total=0;
    private double subTotal;
    private final float iva = (float) 0.19;

    /**
     * Creates new form GUIProductos
     * @param control
     */
    public GUIProductos(ControlFacturacion control) {
        this.control = control;
        data = control.mostrarProducto();
        dtm = new DefaultTableModel(data, columnas);
        
        initComponents();
        tablaProductos.setModel(dtm);
        tablaProductos.repaint();
        
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProductos = new javax.swing.JPanel();
        lbNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        lbCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelProductos.setBackground(new java.awt.Color(25, 65, 81));

        lbNombre.setForeground(new java.awt.Color(255, 255, 255));
        lbNombre.setText("NOMBRE:");

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        btnAgregar.setForeground(new java.awt.Color(25, 65, 81));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas_opt.png"))); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCancelar.setForeground(new java.awt.Color(25, 65, 81));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar (1)_opt.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PRODUCTOS");

        btnBuscar.setForeground(new java.awt.Color(25, 65, 81));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lbCantidad.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lbCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lbCantidad.setText("Cantidad:");

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addComponent(lbNombre)
                        .addGap(33, 33, 33)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar))
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addComponent(lbCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnCancelar)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCantidad))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(txtNombre.getText().isEmpty()){
            mostrarProductos();
        }else{
            nombre = txtNombre.getText();
            producto = control.buscarProducto(nombre);
            if(producto != null){
                mostrarProductos(producto);              
            }else{
                JOptionPane.showMessageDialog(this, "No se encontro producto con ese nombre");
            }            
        }
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        int filaSelecionada = tablaProductos.getSelectedRow();
        if(!txtCantidad.getText().isEmpty()) {
            if(filaSelecionada == -1){
                JOptionPane.showMessageDialog(this, "Debe selecionar un producto","Advertencia",JOptionPane.WARNING_MESSAGE);
            }else{
                codigo = Integer.parseInt(tablaProductos.getValueAt(filaSelecionada, 0).toString());
                nombre = tablaProductos.getValueAt(filaSelecionada, 1).toString();
                precio = Double.parseDouble(tablaProductos.getValueAt(filaSelecionada, 2).toString());
                cantidad = Integer.parseInt(txtCantidad.getText());
                
                int validarCantidad = esNumero(txtCantidad.getText());
                producto = control.buscarProducto(nombre);
                if(validarCantidad != -1 && validarCantidad <= producto.getCantidad()){
                    boolean agregar = control.agregarProductoPedido(codigo,nombre,precio,cantidad,descripcion);
                    if(agregar){
                        dtm = (DefaultTableModel) GUIFacturacion.tablaProductosPedido.getModel();
                        String filaProducto[] = {String.valueOf(codigo), nombre, String.valueOf(precio), String.valueOf(cantidad)};
                        dtm.addRow(filaProducto);
                        
                        producto.setCantidad(producto.getCantidad() - cantidad);
                        mostrarProductos();
                        actualizarDetalleFactura();
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "La cantidad debe ser un numero entero y debe verificar la cantidad disponible del propucto","Aviso",JOptionPane.WARNING_MESSAGE);
                }
                limpiar();
            }            
        } else{
            JOptionPane.showMessageDialog(this, "Debe elegir una cantidad", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed
    
    public void actualizarDetalleFactura(){
        double costoProducto;
        float ivaProducto;
        costoProducto = (precio) * (cantidad);
        total = total + costoProducto;
        ivaProducto = (float) (iva * total);        
        subTotal = total - ivaProducto;
        enviarDetalleFactura(ivaProducto);
    }
    
    public void enviarDetalleFactura(float ivaProducto){
        String subTotalFormat = String.format("%.0f", subTotal);
        GUIFacturacion.txtSubtotal.setText(subTotalFormat);
        String ivaProductoFormat = String.format("%.0f", ivaProducto);
        GUIFacturacion.txtIva.setText(ivaProductoFormat);
        String totalFormat = String.format("%.0f", total);
        GUIFacturacion.txtTotal.setText(totalFormat);
    }
    
    public void mostrarProductos(){
        data = control.mostrarProducto();
        dtm = new DefaultTableModel(data, columnas);
        tablaProductos.setModel(dtm);
        tablaProductos.repaint();
        limpiar();
    }
    
    public void mostrarProductos(Producto producto){
        data = control.mostrarProducto(producto);
        dtm = new DefaultTableModel(data, columnas);
        tablaProductos.setModel(dtm);
        tablaProductos.repaint();
    }
    
    private int esNumero(String entrada){
        int numero;
        try{
            numero = Integer.parseInt(entrada);
            return numero;
        }catch(NumberFormatException nfe){
            return -1;
        }
    }
    
    public void limpiar(){
        txtCantidad.setText("");
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new GUIProductos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCantidad;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
