/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author cezun
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloPrincipal = new javax.swing.JLabel();
        btnProducto = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnFacturacion = new javax.swing.JButton();
        lbProducto = new javax.swing.JLabel();
        lbUsuarios = new javax.swing.JLabel();
        lbReportes = new javax.swing.JLabel();
        lbVentas = new javax.swing.JLabel();
        lbFacturacion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(25, 65, 81));
        setMinimumSize(new java.awt.Dimension(450, 450));
        setPreferredSize(new java.awt.Dimension(570, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTituloPrincipal.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lbTituloPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lbTituloPrincipal.setText("PANEL PRINCIPAL");
        getContentPane().add(lbTituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 180, 30));

        btnProducto.setBackground(new java.awt.Color(25, 65, 81));
        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/product.png"))); // NOI18N
        btnProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, null));
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 120, 120));
        btnProducto.getAccessibleContext().setAccessibleDescription("");

        btnUsuarios.setBackground(new java.awt.Color(25, 65, 81));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios.png"))); // NOI18N
        btnUsuarios.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 120, 120));

        btnReportes.setBackground(new java.awt.Color(25, 65, 81));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        btnReportes.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 120, 120));

        btnVentas.setBackground(new java.awt.Color(25, 65, 81));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas.png"))); // NOI18N
        btnVentas.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 140, 120));

        btnFacturacion.setBackground(new java.awt.Color(25, 65, 81));
        btnFacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/facturacion.png"))); // NOI18N
        btnFacturacion.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        btnFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 140, 120));

        lbProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbProducto.setForeground(new java.awt.Color(255, 255, 255));
        lbProducto.setText("Productos");
        getContentPane().add(lbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        lbUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        lbUsuarios.setText("Clientes");
        getContentPane().add(lbUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        lbReportes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbReportes.setForeground(new java.awt.Color(255, 255, 255));
        lbReportes.setText("Reportes");
        getContentPane().add(lbReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        lbVentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbVentas.setForeground(new java.awt.Color(255, 255, 255));
        lbVentas.setText("Ventas");
        getContentPane().add(lbVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        lbFacturacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbFacturacion.setForeground(new java.awt.Color(255, 255, 255));
        lbFacturacion.setText("Facturación");
        getContentPane().add(lbFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        jPanel2.setBackground(new java.awt.Color(25, 65, 81));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        // TODO add your handling code here:
        GUIAdministrarProducto guiAdmProductos = new GUIAdministrarProducto();
        guiAdmProductos.setVisible(true);
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        GUICliente guiCliente = new GUICliente();
        guiCliente.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "En construcción...");
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "En construcción...");
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionActionPerformed
        // TODO add your handling code here:
        GUIFacturacion guiFacturacion = new GUIFacturacion();
        guiFacturacion.setVisible(true);
    }//GEN-LAST:event_btnFacturacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUIPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFacturacion;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVentas;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbFacturacion;
    private javax.swing.JLabel lbProducto;
    private javax.swing.JLabel lbReportes;
    private javax.swing.JLabel lbTituloPrincipal;
    private javax.swing.JLabel lbUsuarios;
    private javax.swing.JLabel lbVentas;
    // End of variables declaration//GEN-END:variables
}
